# Generated by Django 5.0 on 2024-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_movie_budget_alter_movie_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True, default=1000000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
