# Generated by Django 5.0 on 2024-01-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_alter_movie_budget_alter_movie_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Тарантино', max_length=100),
        ),
    ]
