# Generated by Django 5.0 on 2024-01-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_directors_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
    ]
